[package]
name = "egor00f/testlib"

description = "Small unit tests library"

version = "0.1.4"

registry = "https://github.com/UpliftGames/wally-index"

realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/TestLib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["TestLib test.rbxl", "test.project.json"]

private = false

[dependencies]
stdlib = "egor00f/stdlib@0.1.2"

[server-dependencies]


[dev-dependencies]

