[package]
name = "egor00f/testlib"

description = "Small unit tests library"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/TestLib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["TestLib.rbxl"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]

